apiVersion: v2
name: serve-invenio
appVersion: 12.0.10
description: Turn-key research data management platform customized for ScilifeLab Serve.
home: https://inveniosoftware.org/
icon: https://inveniosoftware.org/static/img/logo-invenio-white.svg
sources:
  - https://github.com/inveniosoftware/invenio-app-rdm
keywords:
  - digital-repository
  - institutional-repository
  - multimedia-library
  - multimedia-repository
type: application
version: 1.0.0
# Add these annotations for OCI
annotations:
  artifacthub.io/changes: |
    - Initial release
    - Production-ready configuration
    - External service integration
  artifacthub.io/images: |
    - name: invenio
      image: ghcr.io/inveniosoftware/demo-inveniordm/demo-inveniordm:12.0.10
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: InvenioRDM Documentation
      url: https://inveniordm.docs.cern.ch/
    - name: Source Code
      url: https://github.com/ScilifelabDataCentre/serve-invenio
maintainers:
  - name: Team Whale
    email: serve@scilifelab.se
dependencies:
  - name: opensearch
    condition: opensearch.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "1.4.0"
  - name: postgresql
    condition: postgresql.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "14.3.3"
  - name: rabbitmq
    condition: rabbitmq.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "12.9.3"
  - name: redis
    condition: redis.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "18.12.0"
